-- CreateTable
CREATE TABLE `SiteSettings` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sectionName` VARCHAR(191) NOT NULL DEFAULT 'site-settings',
    `brandName` VARCHAR(191) NULL,
    `siteName` VARCHAR(191) NULL,
    `siteDescription` TEXT NULL,
    `logo` VARCHAR(191) NULL,
    `favicon` VARCHAR(191) NULL,
    `ogImage` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,
    `mobilePhone` VARCHAR(191) NULL,
    `whatsAppNumber` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `address` TEXT NULL,
    `facebookUrl` VARCHAR(191) NULL,
    `instagramUrl` VARCHAR(191) NULL,
    `twitterUrl` VARCHAR(191) NULL,
    `linkedinUrl` VARCHAR(191) NULL,
    `youtubeUrl` VARCHAR(191) NULL,
    `githubUrl` VARCHAR(191) NULL,
    `googleAnalyticsId` VARCHAR(191) NULL,
    `googleTagManagerId` VARCHAR(191) NULL,
    `googleAdsenseId` VARCHAR(191) NULL,
    `footerText` TEXT NULL,
    `copyrightText` VARCHAR(191) NULL,
    `workingHours` TEXT NULL,
    `googleMapsEmbed` TEXT NULL,
    `metaTitle` VARCHAR(191) NULL,
    `metaDescription` TEXT NULL,
    `metaKeywords` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `SiteSettings_sectionName_key`(`sectionName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
